---
- name: init servers
  hosts: all
  roles:
    - role: adduser
      vars:
        state: present
  tags: 
    - init_servers

- name: reset servers
  hosts: all
  roles:
    - role: adduser
      vars:
        state: absent
  tags: 
    - reset_servers