---
- name: init servers
  hosts: all
  roles:
    - role: adduser
    - role: common
  vars:
    my_action: install
  tags: 
    - init_servers

- name: reset servers
  hosts: all
  roles:
    - role: adduser
    - role: common
  vars:
    my_action: uninstall
  tags: 
    - reset_servers