---
- name: User | Create User Group
  group:
    name: "{{group}}"
    state: present
  when: action == "install"

- name: User | Create User
  user:
    name: "{{user}}"
    comment: local admin
    createhome: yes
    groups: "{{group}}"
    home: "/home/{{user}}"
    shell: /bin/bash
  when: action == "install"

- name: User | Remove User
  user:
    name: "{{user}}"
    state: absent
    remove: yes
  when: my_action == "uninstall"

- name: User | Remove Group
  group:
    name: "{{group}}"
    state: absent
  when: my_action == "uninstall"

- name: User | Add sudoers
  vars:
    content: "'{{user}} localhost = (root) NOPASSWD: /usr/bin/sh'"
    file_name: "/etc/sudoers"
  shell: "grep -qxF {{content}} {{file_name}} || echo {{content}} >> {{file_name}}"
  when: my_action == "install"

- name: User | Remove sudoers
  lineinfile: 
    path: /etc/sudoers
    regexp: "^{{user}}"
    state: absent
  when: my_action == "uninstall"

